// <auto-generated />
using EasyChords.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyChords.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200617210942_IntialMigration")]
    partial class IntialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyChords.Models.Chord", b =>
                {
                    b.Property<int>("ChordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChordName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFlat")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMajor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMinor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNatural")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSharp")
                        .HasColumnType("bit");

                    b.Property<int>("MusicalKeyId")
                        .HasColumnType("int");

                    b.HasKey("ChordId");

                    b.HasIndex("MusicalKeyId");

                    b.ToTable("Chords");
                });

            modelBuilder.Entity("EasyChords.Models.MusicalKey", b =>
                {
                    b.Property<int>("MusicalKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsFlat")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMajor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNatural")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSharp")
                        .HasColumnType("bit");

                    b.Property<string>("MusicalKeyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusicalKeyId");

                    b.ToTable("MusicalKeys");
                });

            modelBuilder.Entity("EasyChords.Models.Chord", b =>
                {
                    b.HasOne("EasyChords.Models.MusicalKey", "MusicalKey")
                        .WithMany("Chords")
                        .HasForeignKey("MusicalKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
